// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: umsg.proto

#include "umsg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_umsg_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_umsg_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Initial_msg_Cmd;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_umsg_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Initial_msg_Prm;
}  // namespace protobuf_umsg_2eproto
namespace vcf {
class Initial_msg_CmdDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Initial_msg_Cmd>
      _instance;
} _Initial_msg_Cmd_default_instance_;
class Initial_msg_PrmDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Initial_msg_Prm>
      _instance;
} _Initial_msg_Prm_default_instance_;
class Initial_msgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Initial_msg>
      _instance;
} _Initial_msg_default_instance_;
class Operational_msgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Operational_msg>
      _instance;
} _Operational_msg_default_instance_;
}  // namespace vcf
namespace protobuf_umsg_2eproto {
static void InitDefaultsInitial_msg_Cmd() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::vcf::_Initial_msg_Cmd_default_instance_;
    new (ptr) ::vcf::Initial_msg_Cmd();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::vcf::Initial_msg_Cmd::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Initial_msg_Cmd =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsInitial_msg_Cmd}, {}};

static void InitDefaultsInitial_msg_Prm() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::vcf::_Initial_msg_Prm_default_instance_;
    new (ptr) ::vcf::Initial_msg_Prm();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::vcf::Initial_msg_Prm::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Initial_msg_Prm =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsInitial_msg_Prm}, {}};

static void InitDefaultsInitial_msg() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::vcf::_Initial_msg_default_instance_;
    new (ptr) ::vcf::Initial_msg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::vcf::Initial_msg::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_Initial_msg =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsInitial_msg}, {
      &protobuf_umsg_2eproto::scc_info_Initial_msg_Cmd.base,
      &protobuf_umsg_2eproto::scc_info_Initial_msg_Prm.base,}};

static void InitDefaultsOperational_msg() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::vcf::_Operational_msg_default_instance_;
    new (ptr) ::vcf::Operational_msg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::vcf::Operational_msg::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Operational_msg =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsOperational_msg}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Initial_msg_Cmd.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Initial_msg_Prm.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Initial_msg.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Operational_msg.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg_Cmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg_Cmd, _from_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg_Cmd, _name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg_Cmd, _value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg_Prm, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg_Prm, _vartype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg_Prm, _min_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg_Prm, _max_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg, _seqno_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg, _version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg, _result_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg, _msg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg, cmd_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg, prm_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Initial_msg, _cycle_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Operational_msg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Operational_msg, _seqno_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Operational_msg, _from_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Operational_msg, _to_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Operational_msg, _name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Operational_msg, _value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Operational_msg, _result_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vcf::Operational_msg, _msg_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::vcf::Initial_msg_Cmd)},
  { 8, -1, sizeof(::vcf::Initial_msg_Prm)},
  { 16, -1, sizeof(::vcf::Initial_msg)},
  { 28, -1, sizeof(::vcf::Operational_msg)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::vcf::_Initial_msg_Cmd_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::vcf::_Initial_msg_Prm_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::vcf::_Initial_msg_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::vcf::_Operational_msg_default_instance_),
};

static void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "umsg.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

static void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

static void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\numsg.proto\022\003vcf\"\216\002\n\013Initial_msg\022\016\n\006_se"
      "qNo\030\001 \001(\r\022\020\n\010_version\030\002 \001(\r\022\017\n\007_result\030\003"
      " \001(\005\022\014\n\004_msg\030\004 \001(\t\022!\n\003cmd\030\005 \003(\0132\024.vcf.In"
      "itial_msg.Cmd\022!\n\003prm\030\006 \003(\0132\024.vcf.Initial"
      "_msg.Prm\022\016\n\006_cycle\030\007 \001(\r\0323\n\003Cmd\022\r\n\005_from"
      "\030\001 \001(\r\022\r\n\005_name\030\002 \001(\t\022\016\n\006_value\030\004 \001(\001\0323\n"
      "\003Prm\022\020\n\010_vartype\030\001 \001(\r\022\014\n\004_min\030\002 \001(\005\022\014\n\004"
      "_max\030\003 \001(\005\"{\n\017Operational_msg\022\016\n\006_seqNo\030"
      "\001 \001(\r\022\r\n\005_from\030\002 \001(\r\022\013\n\003_to\030\003 \001(\r\022\r\n\005_na"
      "me\030\004 \001(\t\022\016\n\006_value\030\005 \001(\001\022\017\n\007_result\030\006 \001("
      "\005\022\014\n\004_msg\030\007 \001(\tB\035\n\017com.rubicom.vcfB\nUmsg"
      "Protosb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 454);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "umsg.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_umsg_2eproto
namespace vcf {

// ===================================================================

void Initial_msg_Cmd::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Initial_msg_Cmd::kFromFieldNumber;
const int Initial_msg_Cmd::kNameFieldNumber;
const int Initial_msg_Cmd::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Initial_msg_Cmd::Initial_msg_Cmd()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_umsg_2eproto::scc_info_Initial_msg_Cmd.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:vcf.Initial_msg.Cmd)
}
Initial_msg_Cmd::Initial_msg_Cmd(const Initial_msg_Cmd& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  _name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from._name().size() > 0) {
    _name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._name_);
  }
  ::memcpy(&_value_, &from._value_,
    static_cast<size_t>(reinterpret_cast<char*>(&_from_) -
    reinterpret_cast<char*>(&_value_)) + sizeof(_from_));
  // @@protoc_insertion_point(copy_constructor:vcf.Initial_msg.Cmd)
}

void Initial_msg_Cmd::SharedCtor() {
  _name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&_value_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_from_) -
      reinterpret_cast<char*>(&_value_)) + sizeof(_from_));
}

Initial_msg_Cmd::~Initial_msg_Cmd() {
  // @@protoc_insertion_point(destructor:vcf.Initial_msg.Cmd)
  SharedDtor();
}

void Initial_msg_Cmd::SharedDtor() {
  _name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Initial_msg_Cmd::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Initial_msg_Cmd::descriptor() {
  ::protobuf_umsg_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_umsg_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Initial_msg_Cmd& Initial_msg_Cmd::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_umsg_2eproto::scc_info_Initial_msg_Cmd.base);
  return *internal_default_instance();
}


void Initial_msg_Cmd::Clear() {
// @@protoc_insertion_point(message_clear_start:vcf.Initial_msg.Cmd)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&_value_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_from_) -
      reinterpret_cast<char*>(&_value_)) + sizeof(_from_));
  _internal_metadata_.Clear();
}

bool Initial_msg_Cmd::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:vcf.Initial_msg.Cmd)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 _from = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &_from_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string _name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->_name().data(), static_cast<int>(this->_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "vcf.Initial_msg.Cmd._name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double _value = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &_value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:vcf.Initial_msg.Cmd)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:vcf.Initial_msg.Cmd)
  return false;
#undef DO_
}

void Initial_msg_Cmd::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:vcf.Initial_msg.Cmd)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 _from = 1;
  if (this->_from() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->_from(), output);
  }

  // string _name = 2;
  if (this->_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_name().data(), static_cast<int>(this->_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "vcf.Initial_msg.Cmd._name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->_name(), output);
  }

  // double _value = 4;
  if (this->_value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->_value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:vcf.Initial_msg.Cmd)
}

::google::protobuf::uint8* Initial_msg_Cmd::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:vcf.Initial_msg.Cmd)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 _from = 1;
  if (this->_from() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->_from(), target);
  }

  // string _name = 2;
  if (this->_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_name().data(), static_cast<int>(this->_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "vcf.Initial_msg.Cmd._name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->_name(), target);
  }

  // double _value = 4;
  if (this->_value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->_value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vcf.Initial_msg.Cmd)
  return target;
}

size_t Initial_msg_Cmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:vcf.Initial_msg.Cmd)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string _name = 2;
  if (this->_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->_name());
  }

  // double _value = 4;
  if (this->_value() != 0) {
    total_size += 1 + 8;
  }

  // uint32 _from = 1;
  if (this->_from() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->_from());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Initial_msg_Cmd::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:vcf.Initial_msg.Cmd)
  GOOGLE_DCHECK_NE(&from, this);
  const Initial_msg_Cmd* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Initial_msg_Cmd>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:vcf.Initial_msg.Cmd)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:vcf.Initial_msg.Cmd)
    MergeFrom(*source);
  }
}

void Initial_msg_Cmd::MergeFrom(const Initial_msg_Cmd& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:vcf.Initial_msg.Cmd)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._name().size() > 0) {

    _name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._name_);
  }
  if (from._value() != 0) {
    set__value(from._value());
  }
  if (from._from() != 0) {
    set__from(from._from());
  }
}

void Initial_msg_Cmd::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:vcf.Initial_msg.Cmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Initial_msg_Cmd::CopyFrom(const Initial_msg_Cmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vcf.Initial_msg.Cmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Initial_msg_Cmd::IsInitialized() const {
  return true;
}

void Initial_msg_Cmd::Swap(Initial_msg_Cmd* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Initial_msg_Cmd::InternalSwap(Initial_msg_Cmd* other) {
  using std::swap;
  _name_.Swap(&other->_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(_value_, other->_value_);
  swap(_from_, other->_from_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Initial_msg_Cmd::GetMetadata() const {
  protobuf_umsg_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_umsg_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Initial_msg_Prm::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Initial_msg_Prm::kVartypeFieldNumber;
const int Initial_msg_Prm::kMinFieldNumber;
const int Initial_msg_Prm::kMaxFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Initial_msg_Prm::Initial_msg_Prm()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_umsg_2eproto::scc_info_Initial_msg_Prm.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:vcf.Initial_msg.Prm)
}
Initial_msg_Prm::Initial_msg_Prm(const Initial_msg_Prm& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&_vartype_, &from._vartype_,
    static_cast<size_t>(reinterpret_cast<char*>(&_max_) -
    reinterpret_cast<char*>(&_vartype_)) + sizeof(_max_));
  // @@protoc_insertion_point(copy_constructor:vcf.Initial_msg.Prm)
}

void Initial_msg_Prm::SharedCtor() {
  ::memset(&_vartype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_max_) -
      reinterpret_cast<char*>(&_vartype_)) + sizeof(_max_));
}

Initial_msg_Prm::~Initial_msg_Prm() {
  // @@protoc_insertion_point(destructor:vcf.Initial_msg.Prm)
  SharedDtor();
}

void Initial_msg_Prm::SharedDtor() {
}

void Initial_msg_Prm::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Initial_msg_Prm::descriptor() {
  ::protobuf_umsg_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_umsg_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Initial_msg_Prm& Initial_msg_Prm::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_umsg_2eproto::scc_info_Initial_msg_Prm.base);
  return *internal_default_instance();
}


void Initial_msg_Prm::Clear() {
// @@protoc_insertion_point(message_clear_start:vcf.Initial_msg.Prm)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_vartype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_max_) -
      reinterpret_cast<char*>(&_vartype_)) + sizeof(_max_));
  _internal_metadata_.Clear();
}

bool Initial_msg_Prm::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:vcf.Initial_msg.Prm)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 _vartype = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &_vartype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 _min = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &_min_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 _max = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &_max_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:vcf.Initial_msg.Prm)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:vcf.Initial_msg.Prm)
  return false;
#undef DO_
}

void Initial_msg_Prm::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:vcf.Initial_msg.Prm)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 _vartype = 1;
  if (this->_vartype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->_vartype(), output);
  }

  // int32 _min = 2;
  if (this->_min() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->_min(), output);
  }

  // int32 _max = 3;
  if (this->_max() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->_max(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:vcf.Initial_msg.Prm)
}

::google::protobuf::uint8* Initial_msg_Prm::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:vcf.Initial_msg.Prm)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 _vartype = 1;
  if (this->_vartype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->_vartype(), target);
  }

  // int32 _min = 2;
  if (this->_min() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->_min(), target);
  }

  // int32 _max = 3;
  if (this->_max() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->_max(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vcf.Initial_msg.Prm)
  return target;
}

size_t Initial_msg_Prm::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:vcf.Initial_msg.Prm)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 _vartype = 1;
  if (this->_vartype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->_vartype());
  }

  // int32 _min = 2;
  if (this->_min() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->_min());
  }

  // int32 _max = 3;
  if (this->_max() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->_max());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Initial_msg_Prm::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:vcf.Initial_msg.Prm)
  GOOGLE_DCHECK_NE(&from, this);
  const Initial_msg_Prm* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Initial_msg_Prm>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:vcf.Initial_msg.Prm)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:vcf.Initial_msg.Prm)
    MergeFrom(*source);
  }
}

void Initial_msg_Prm::MergeFrom(const Initial_msg_Prm& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:vcf.Initial_msg.Prm)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._vartype() != 0) {
    set__vartype(from._vartype());
  }
  if (from._min() != 0) {
    set__min(from._min());
  }
  if (from._max() != 0) {
    set__max(from._max());
  }
}

void Initial_msg_Prm::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:vcf.Initial_msg.Prm)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Initial_msg_Prm::CopyFrom(const Initial_msg_Prm& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vcf.Initial_msg.Prm)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Initial_msg_Prm::IsInitialized() const {
  return true;
}

void Initial_msg_Prm::Swap(Initial_msg_Prm* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Initial_msg_Prm::InternalSwap(Initial_msg_Prm* other) {
  using std::swap;
  swap(_vartype_, other->_vartype_);
  swap(_min_, other->_min_);
  swap(_max_, other->_max_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Initial_msg_Prm::GetMetadata() const {
  protobuf_umsg_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_umsg_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Initial_msg::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Initial_msg::kSeqNoFieldNumber;
const int Initial_msg::kVersionFieldNumber;
const int Initial_msg::kResultFieldNumber;
const int Initial_msg::kMsgFieldNumber;
const int Initial_msg::kCmdFieldNumber;
const int Initial_msg::kPrmFieldNumber;
const int Initial_msg::kCycleFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Initial_msg::Initial_msg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_umsg_2eproto::scc_info_Initial_msg.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:vcf.Initial_msg)
}
Initial_msg::Initial_msg(const Initial_msg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      cmd_(from.cmd_),
      prm_(from.prm_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  _msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from._msg().size() > 0) {
    _msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._msg_);
  }
  ::memcpy(&_seqno_, &from._seqno_,
    static_cast<size_t>(reinterpret_cast<char*>(&_cycle_) -
    reinterpret_cast<char*>(&_seqno_)) + sizeof(_cycle_));
  // @@protoc_insertion_point(copy_constructor:vcf.Initial_msg)
}

void Initial_msg::SharedCtor() {
  _msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&_seqno_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_cycle_) -
      reinterpret_cast<char*>(&_seqno_)) + sizeof(_cycle_));
}

Initial_msg::~Initial_msg() {
  // @@protoc_insertion_point(destructor:vcf.Initial_msg)
  SharedDtor();
}

void Initial_msg::SharedDtor() {
  _msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Initial_msg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Initial_msg::descriptor() {
  ::protobuf_umsg_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_umsg_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Initial_msg& Initial_msg::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_umsg_2eproto::scc_info_Initial_msg.base);
  return *internal_default_instance();
}


void Initial_msg::Clear() {
// @@protoc_insertion_point(message_clear_start:vcf.Initial_msg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cmd_.Clear();
  prm_.Clear();
  _msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&_seqno_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_cycle_) -
      reinterpret_cast<char*>(&_seqno_)) + sizeof(_cycle_));
  _internal_metadata_.Clear();
}

bool Initial_msg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:vcf.Initial_msg)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 _seqNo = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &_seqno_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 _version = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &_version_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 _result = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &_result_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string _msg = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__msg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->_msg().data(), static_cast<int>(this->_msg().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "vcf.Initial_msg._msg"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .vcf.Initial_msg.Cmd cmd = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_cmd()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .vcf.Initial_msg.Prm prm = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_prm()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 _cycle = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &_cycle_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:vcf.Initial_msg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:vcf.Initial_msg)
  return false;
#undef DO_
}

void Initial_msg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:vcf.Initial_msg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 _seqNo = 1;
  if (this->_seqno() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->_seqno(), output);
  }

  // uint32 _version = 2;
  if (this->_version() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->_version(), output);
  }

  // int32 _result = 3;
  if (this->_result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->_result(), output);
  }

  // string _msg = 4;
  if (this->_msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_msg().data(), static_cast<int>(this->_msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "vcf.Initial_msg._msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->_msg(), output);
  }

  // repeated .vcf.Initial_msg.Cmd cmd = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->cmd_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->cmd(static_cast<int>(i)),
      output);
  }

  // repeated .vcf.Initial_msg.Prm prm = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->prm_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6,
      this->prm(static_cast<int>(i)),
      output);
  }

  // uint32 _cycle = 7;
  if (this->_cycle() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->_cycle(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:vcf.Initial_msg)
}

::google::protobuf::uint8* Initial_msg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:vcf.Initial_msg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 _seqNo = 1;
  if (this->_seqno() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->_seqno(), target);
  }

  // uint32 _version = 2;
  if (this->_version() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->_version(), target);
  }

  // int32 _result = 3;
  if (this->_result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->_result(), target);
  }

  // string _msg = 4;
  if (this->_msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_msg().data(), static_cast<int>(this->_msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "vcf.Initial_msg._msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->_msg(), target);
  }

  // repeated .vcf.Initial_msg.Cmd cmd = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->cmd_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->cmd(static_cast<int>(i)), deterministic, target);
  }

  // repeated .vcf.Initial_msg.Prm prm = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->prm_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->prm(static_cast<int>(i)), deterministic, target);
  }

  // uint32 _cycle = 7;
  if (this->_cycle() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->_cycle(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vcf.Initial_msg)
  return target;
}

size_t Initial_msg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:vcf.Initial_msg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .vcf.Initial_msg.Cmd cmd = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->cmd_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->cmd(static_cast<int>(i)));
    }
  }

  // repeated .vcf.Initial_msg.Prm prm = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->prm_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->prm(static_cast<int>(i)));
    }
  }

  // string _msg = 4;
  if (this->_msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->_msg());
  }

  // uint32 _seqNo = 1;
  if (this->_seqno() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->_seqno());
  }

  // uint32 _version = 2;
  if (this->_version() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->_version());
  }

  // int32 _result = 3;
  if (this->_result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->_result());
  }

  // uint32 _cycle = 7;
  if (this->_cycle() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->_cycle());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Initial_msg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:vcf.Initial_msg)
  GOOGLE_DCHECK_NE(&from, this);
  const Initial_msg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Initial_msg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:vcf.Initial_msg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:vcf.Initial_msg)
    MergeFrom(*source);
  }
}

void Initial_msg::MergeFrom(const Initial_msg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:vcf.Initial_msg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cmd_.MergeFrom(from.cmd_);
  prm_.MergeFrom(from.prm_);
  if (from._msg().size() > 0) {

    _msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._msg_);
  }
  if (from._seqno() != 0) {
    set__seqno(from._seqno());
  }
  if (from._version() != 0) {
    set__version(from._version());
  }
  if (from._result() != 0) {
    set__result(from._result());
  }
  if (from._cycle() != 0) {
    set__cycle(from._cycle());
  }
}

void Initial_msg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:vcf.Initial_msg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Initial_msg::CopyFrom(const Initial_msg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vcf.Initial_msg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Initial_msg::IsInitialized() const {
  return true;
}

void Initial_msg::Swap(Initial_msg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Initial_msg::InternalSwap(Initial_msg* other) {
  using std::swap;
  CastToBase(&cmd_)->InternalSwap(CastToBase(&other->cmd_));
  CastToBase(&prm_)->InternalSwap(CastToBase(&other->prm_));
  _msg_.Swap(&other->_msg_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(_seqno_, other->_seqno_);
  swap(_version_, other->_version_);
  swap(_result_, other->_result_);
  swap(_cycle_, other->_cycle_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Initial_msg::GetMetadata() const {
  protobuf_umsg_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_umsg_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Operational_msg::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Operational_msg::kSeqNoFieldNumber;
const int Operational_msg::kFromFieldNumber;
const int Operational_msg::kToFieldNumber;
const int Operational_msg::kNameFieldNumber;
const int Operational_msg::kValueFieldNumber;
const int Operational_msg::kResultFieldNumber;
const int Operational_msg::kMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Operational_msg::Operational_msg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_umsg_2eproto::scc_info_Operational_msg.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:vcf.Operational_msg)
}
Operational_msg::Operational_msg(const Operational_msg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  _name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from._name().size() > 0) {
    _name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._name_);
  }
  _msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from._msg().size() > 0) {
    _msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._msg_);
  }
  ::memcpy(&_seqno_, &from._seqno_,
    static_cast<size_t>(reinterpret_cast<char*>(&_value_) -
    reinterpret_cast<char*>(&_seqno_)) + sizeof(_value_));
  // @@protoc_insertion_point(copy_constructor:vcf.Operational_msg)
}

void Operational_msg::SharedCtor() {
  _name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&_seqno_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_value_) -
      reinterpret_cast<char*>(&_seqno_)) + sizeof(_value_));
}

Operational_msg::~Operational_msg() {
  // @@protoc_insertion_point(destructor:vcf.Operational_msg)
  SharedDtor();
}

void Operational_msg::SharedDtor() {
  _name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Operational_msg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Operational_msg::descriptor() {
  ::protobuf_umsg_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_umsg_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Operational_msg& Operational_msg::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_umsg_2eproto::scc_info_Operational_msg.base);
  return *internal_default_instance();
}


void Operational_msg::Clear() {
// @@protoc_insertion_point(message_clear_start:vcf.Operational_msg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&_seqno_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_value_) -
      reinterpret_cast<char*>(&_seqno_)) + sizeof(_value_));
  _internal_metadata_.Clear();
}

bool Operational_msg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:vcf.Operational_msg)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 _seqNo = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &_seqno_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 _from = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &_from_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 _to = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &_to_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string _name = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->_name().data(), static_cast<int>(this->_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "vcf.Operational_msg._name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double _value = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &_value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 _result = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &_result_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string _msg = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__msg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->_msg().data(), static_cast<int>(this->_msg().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "vcf.Operational_msg._msg"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:vcf.Operational_msg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:vcf.Operational_msg)
  return false;
#undef DO_
}

void Operational_msg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:vcf.Operational_msg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 _seqNo = 1;
  if (this->_seqno() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->_seqno(), output);
  }

  // uint32 _from = 2;
  if (this->_from() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->_from(), output);
  }

  // uint32 _to = 3;
  if (this->_to() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->_to(), output);
  }

  // string _name = 4;
  if (this->_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_name().data(), static_cast<int>(this->_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "vcf.Operational_msg._name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->_name(), output);
  }

  // double _value = 5;
  if (this->_value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->_value(), output);
  }

  // int32 _result = 6;
  if (this->_result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->_result(), output);
  }

  // string _msg = 7;
  if (this->_msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_msg().data(), static_cast<int>(this->_msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "vcf.Operational_msg._msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->_msg(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:vcf.Operational_msg)
}

::google::protobuf::uint8* Operational_msg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:vcf.Operational_msg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 _seqNo = 1;
  if (this->_seqno() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->_seqno(), target);
  }

  // uint32 _from = 2;
  if (this->_from() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->_from(), target);
  }

  // uint32 _to = 3;
  if (this->_to() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->_to(), target);
  }

  // string _name = 4;
  if (this->_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_name().data(), static_cast<int>(this->_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "vcf.Operational_msg._name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->_name(), target);
  }

  // double _value = 5;
  if (this->_value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->_value(), target);
  }

  // int32 _result = 6;
  if (this->_result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->_result(), target);
  }

  // string _msg = 7;
  if (this->_msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_msg().data(), static_cast<int>(this->_msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "vcf.Operational_msg._msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->_msg(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vcf.Operational_msg)
  return target;
}

size_t Operational_msg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:vcf.Operational_msg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string _name = 4;
  if (this->_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->_name());
  }

  // string _msg = 7;
  if (this->_msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->_msg());
  }

  // uint32 _seqNo = 1;
  if (this->_seqno() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->_seqno());
  }

  // uint32 _from = 2;
  if (this->_from() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->_from());
  }

  // uint32 _to = 3;
  if (this->_to() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->_to());
  }

  // int32 _result = 6;
  if (this->_result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->_result());
  }

  // double _value = 5;
  if (this->_value() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Operational_msg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:vcf.Operational_msg)
  GOOGLE_DCHECK_NE(&from, this);
  const Operational_msg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Operational_msg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:vcf.Operational_msg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:vcf.Operational_msg)
    MergeFrom(*source);
  }
}

void Operational_msg::MergeFrom(const Operational_msg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:vcf.Operational_msg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._name().size() > 0) {

    _name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._name_);
  }
  if (from._msg().size() > 0) {

    _msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._msg_);
  }
  if (from._seqno() != 0) {
    set__seqno(from._seqno());
  }
  if (from._from() != 0) {
    set__from(from._from());
  }
  if (from._to() != 0) {
    set__to(from._to());
  }
  if (from._result() != 0) {
    set__result(from._result());
  }
  if (from._value() != 0) {
    set__value(from._value());
  }
}

void Operational_msg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:vcf.Operational_msg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Operational_msg::CopyFrom(const Operational_msg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vcf.Operational_msg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Operational_msg::IsInitialized() const {
  return true;
}

void Operational_msg::Swap(Operational_msg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Operational_msg::InternalSwap(Operational_msg* other) {
  using std::swap;
  _name_.Swap(&other->_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _msg_.Swap(&other->_msg_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(_seqno_, other->_seqno_);
  swap(_from_, other->_from_);
  swap(_to_, other->_to_);
  swap(_result_, other->_result_);
  swap(_value_, other->_value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Operational_msg::GetMetadata() const {
  protobuf_umsg_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_umsg_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace vcf
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::vcf::Initial_msg_Cmd* Arena::CreateMaybeMessage< ::vcf::Initial_msg_Cmd >(Arena* arena) {
  return Arena::CreateInternal< ::vcf::Initial_msg_Cmd >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::vcf::Initial_msg_Prm* Arena::CreateMaybeMessage< ::vcf::Initial_msg_Prm >(Arena* arena) {
  return Arena::CreateInternal< ::vcf::Initial_msg_Prm >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::vcf::Initial_msg* Arena::CreateMaybeMessage< ::vcf::Initial_msg >(Arena* arena) {
  return Arena::CreateInternal< ::vcf::Initial_msg >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::vcf::Operational_msg* Arena::CreateMaybeMessage< ::vcf::Operational_msg >(Arena* arena) {
  return Arena::CreateInternal< ::vcf::Operational_msg >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
